import { describe, expect, it } from "vitest";
import {
  BusinessBrain,
  BusinessHealth,
  DefaultBusinessHealthEvaluator,
  DefaultBusinessInsightGenerator,
  DefaultKnowledgeGraphBuilder,
  DefaultOpportunityDetector,
  InMemoryBusinessBrainRepository,
  InsightGenerationResult,
  OpportunityDetectionResult,
  createKnowledgeGraphSnapshot,
  type BusinessBrainId,
  type BusinessBrainRepository,
  type BusinessHealthEvaluator,
  type BusinessInsightGenerator,
  type BusinessBrainSnapshot,
  type BusinessProfileId,
  type KnowledgeGraphBuilder,
  type ObservationId,
  type OpportunityDetector,
  type OpportunityId,
  type RiskId,
} from "@nextshift/domain";
import type { BusinessId, TenantId, Timestamp } from "@nextshift/shared";
import {
  BusinessBrainApplicationService,
  BusinessBrainApplicationService as PublicBusinessBrainApplicationService,
} from "../src";

const businessId = "business-1" as BusinessId;
const tenantId = "tenant-1" as TenantId;
const businessBrainId = "business-brain-1" as BusinessBrainId;
const businessProfileId = "business-profile-1" as BusinessProfileId;
const createdAt = "2026-06-29T00:00:00.000Z";

const context = {
  businessId,
  tenant: { tenantId },
  actor: { actorType: "user" as const },
};

function createBusinessBrain(): BusinessBrain {
  return BusinessBrain.create({
    id: businessBrainId,
    businessProfileId,
    createdAt,
  });
}

function createSignalRichBusinessBrain(): BusinessBrain {
  const businessBrain = createBusinessBrain();

  businessBrain.ingestObservation({
    id: "observation-1" as ObservationId,
    source: "analytics",
    summary: "Lead conversion improved.",
    observedAt: "2026-06-29T01:00:00.000Z",
  });
  businessBrain.addOpportunity({
    id: "opportunity-1" as OpportunityId,
    title: "Scale webinar follow-up",
    summary: "Webinar follow-up can create more qualified sales calls.",
    createdAt: "2026-06-29T02:00:00.000Z",
  });
  businessBrain.addRisk({
    id: "risk-1" as RiskId,
    title: "Revenue concentration",
    summary: "Revenue remains concentrated in one offer.",
    createdAt: "2026-06-29T03:00:00.000Z",
  });

  return businessBrain;
}

class RecordingBusinessBrainRepository implements BusinessBrainRepository {
  readonly requestedIds: BusinessBrainId[] = [];

  constructor(private readonly businessBrain: BusinessBrain | null) {}

  async save(): Promise<void> {
    throw new Error("Save should not be called by analysis.");
  }

  async findById(id: BusinessBrainId): Promise<BusinessBrain | null> {
    this.requestedIds.push(id);
    return this.businessBrain;
  }
}

class RecordingBusinessHealthEvaluator implements BusinessHealthEvaluator {
  snapshots: BusinessBrainSnapshot[] = [];

  evaluate(snapshot: BusinessBrainSnapshot): BusinessHealth {
    this.snapshots.push(snapshot);
    return BusinessHealth.create({
      score: 76,
      dimensions: [
        {
          name: "operations",
          score: 76,
          summary: "Operations are strong.",
        },
      ],
      summary: "Business health is strong.",
      evaluatedAt: snapshot.updatedAt,
    });
  }
}

class RecordingOpportunityDetector implements OpportunityDetector {
  snapshots: BusinessBrainSnapshot[] = [];

  detect(snapshot: BusinessBrainSnapshot): OpportunityDetectionResult {
    this.snapshots.push(snapshot);
    return OpportunityDetectionResult.create({
      opportunities: [],
      detectedAt: snapshot.updatedAt,
      summary: "No opportunities detected by mock.",
    });
  }
}

class RecordingBusinessInsightGenerator implements BusinessInsightGenerator {
  snapshots: BusinessBrainSnapshot[] = [];

  generate(snapshot: BusinessBrainSnapshot): InsightGenerationResult {
    this.snapshots.push(snapshot);
    return InsightGenerationResult.create({
      insights: [],
      generatedAt: snapshot.updatedAt,
      summary: "No insights generated by mock.",
    });
  }
}

class RecordingKnowledgeGraphBuilder implements KnowledgeGraphBuilder {
  snapshots: BusinessBrainSnapshot[] = [];

  build(snapshot: BusinessBrainSnapshot) {
    this.snapshots.push(snapshot);
    return createKnowledgeGraphSnapshot({
      nodes: [],
      relationships: [],
      generatedAt: snapshot.updatedAt,
      summary: "No graph generated by mock.",
    });
  }
}

function fixedNow(): Timestamp {
  return "2026-06-29T10:00:00.000Z";
}

describe("BusinessBrainApplicationService", () => {
  it("orchestrates Business Brain analysis using default domain components", async () => {
    const repository = new InMemoryBusinessBrainRepository();
    const businessBrain = createSignalRichBusinessBrain();
    await repository.save(businessBrain);

    const service = new BusinessBrainApplicationService(
      repository,
      new DefaultBusinessHealthEvaluator(),
      new DefaultOpportunityDetector(),
      new DefaultBusinessInsightGenerator(),
      new DefaultKnowledgeGraphBuilder(),
      fixedNow
    );

    const result = await service.analyzeBusinessBrain({
      queryType: "AnalyzeBusinessBrain",
      context,
      businessBrainId,
    });

    expect(result.ok).toBe(true);

    if (result.ok) {
      expect(result.value.analyzedAt).toBe("2026-06-29T10:00:00.000Z");
      expect(result.value.businessHealth.toSnapshot()).toMatchObject({
        status: "stable",
      });
      expect(
        result.value.opportunityDetectionResult.toSnapshot().opportunities
      ).toHaveLength(1);
      expect(
        result.value.insightGenerationResult.toSnapshot().insights
      ).toHaveLength(2);
      expect(result.value.knowledgeGraphSnapshot.nodes).toHaveLength(3);
    }
  });

  it("loads aggregate from repository and passes the same snapshot to dependencies", async () => {
    const businessBrain = createSignalRichBusinessBrain();
    const repository = new RecordingBusinessBrainRepository(businessBrain);
    const healthEvaluator = new RecordingBusinessHealthEvaluator();
    const opportunityDetector = new RecordingOpportunityDetector();
    const insightGenerator = new RecordingBusinessInsightGenerator();
    const knowledgeGraphBuilder = new RecordingKnowledgeGraphBuilder();
    const service = new BusinessBrainApplicationService(
      repository,
      healthEvaluator,
      opportunityDetector,
      insightGenerator,
      knowledgeGraphBuilder,
      fixedNow
    );

    const result = await service.analyzeBusinessBrain({
      queryType: "AnalyzeBusinessBrain",
      context,
      businessBrainId,
    });

    expect(result.ok).toBe(true);
    expect(repository.requestedIds).toEqual([businessBrainId]);
    expect(healthEvaluator.snapshots).toEqual([businessBrain.toSnapshot()]);
    expect(opportunityDetector.snapshots).toEqual([businessBrain.toSnapshot()]);
    expect(insightGenerator.snapshots).toEqual([businessBrain.toSnapshot()]);
    expect(knowledgeGraphBuilder.snapshots).toEqual([
      businessBrain.toSnapshot(),
    ]);
  });

  it("returns not found when repository does not contain the aggregate", async () => {
    const service = new BusinessBrainApplicationService(
      new RecordingBusinessBrainRepository(null),
      new RecordingBusinessHealthEvaluator(),
      new RecordingOpportunityDetector(),
      new RecordingBusinessInsightGenerator(),
      new RecordingKnowledgeGraphBuilder(),
      fixedNow
    );

    const result = await service.analyzeBusinessBrain({
      queryType: "AnalyzeBusinessBrain",
      context,
      businessBrainId,
    });

    expect(result.ok).toBe(false);

    if (!result.ok) {
      expect(result.error).toEqual({
        code: "BusinessBrainNotFound",
        message: "BusinessBrain business-brain-1 was not found.",
      });
    }
  });

  it("maps dependency failures into application errors", async () => {
    const service = new BusinessBrainApplicationService(
      new RecordingBusinessBrainRepository(createBusinessBrain()),
      {
        evaluate() {
          throw new Error("health evaluator failed");
        },
      },
      new RecordingOpportunityDetector(),
      new RecordingBusinessInsightGenerator(),
      new RecordingKnowledgeGraphBuilder(),
      fixedNow
    );

    const result = await service.analyzeBusinessBrain({
      queryType: "AnalyzeBusinessBrain",
      context,
      businessBrainId,
    });

    expect(result.ok).toBe(false);

    if (!result.ok) {
      expect(result.error).toMatchObject({
        code: "BusinessBrainAnalysisFailed",
        message: "health evaluator failed",
      });
    }
  });

  it("validates businessBrainId", async () => {
    const service = new BusinessBrainApplicationService(
      new RecordingBusinessBrainRepository(createBusinessBrain()),
      new RecordingBusinessHealthEvaluator(),
      new RecordingOpportunityDetector(),
      new RecordingBusinessInsightGenerator(),
      new RecordingKnowledgeGraphBuilder(),
      fixedNow
    );

    const result = await service.analyzeBusinessBrain({
      queryType: "AnalyzeBusinessBrain",
      context,
      businessBrainId: " " as BusinessBrainId,
    });

    expect(result.ok).toBe(false);

    if (!result.ok) {
      expect(result.error).toMatchObject({
        code: "BusinessBrainAnalysisFailed",
        message: "BusinessBrain ID is required.",
      });
    }
  });

  it("exports the service from the application package", () => {
    expect(PublicBusinessBrainApplicationService).toBe(
      BusinessBrainApplicationService
    );
  });
  it("does not persist or mutate the BusinessBrain aggregate during analysis", async () => {
    const businessBrain = createSignalRichBusinessBrain();
    const before = businessBrain.toSnapshot();
    const repository = new RecordingBusinessBrainRepository(businessBrain);
    const service = new BusinessBrainApplicationService(
      repository,
      new DefaultBusinessHealthEvaluator(),
      new DefaultOpportunityDetector(),
      new DefaultBusinessInsightGenerator(),
      new DefaultKnowledgeGraphBuilder(),
      fixedNow
    );

    const result = await service.analyzeBusinessBrain({
      queryType: "AnalyzeBusinessBrain",
      context,
      businessBrainId,
    });

    expect(result.ok).toBe(true);
    expect(businessBrain.toSnapshot()).toEqual(before);
  });
});
