// This file is generated by scripts/generate-eslint-boundaries.ts.
// Run `pnpm lint:boundaries:check` to verify it is in sync with src/modules.

const boundaryOverrides = [
  {
    files: ['src/modules/activation/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/activation',
                '!@/modules/activation/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/admin/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/admin',
                '!@/modules/admin/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/agent-runtime/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/agent-runtime',
                '!@/modules/agent-runtime/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/agent-workforce/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/agent-workforce',
                '!@/modules/agent-workforce/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/ai/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/ai-coach/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/ai-coach',
                '!@/modules/ai-coach/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/ai-coo/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/ai-coo',
                '!@/modules/ai-coo/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/analytics/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/analytics',
                '!@/modules/analytics/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/auth/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/auth',
                '!@/modules/auth/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/automation/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/automation',
                '!@/modules/automation/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/autonomous-execution/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/autonomous-execution',
                '!@/modules/autonomous-execution/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/blueprints/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/blueprints',
                '!@/modules/blueprints/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/brand-builder/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/brand-builder',
                '!@/modules/brand-builder/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/brand-discovery/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/brand-discovery',
                '!@/modules/brand-discovery/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/brand-dna/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/brand-dna',
                '!@/modules/brand-dna/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/brand-intelligence/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/brand-intelligence',
                '!@/modules/brand-intelligence/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/business-context-memory/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/business-context-memory',
                '!@/modules/business-context-memory/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/business-intelligence/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/business-intelligence',
                '!@/modules/business-intelligence/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/business-state/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/business-state',
                '!@/modules/business-state/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/business-twin/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/business-twin',
                '!@/modules/business-twin/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/content-engine/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/content-engine',
                '!@/modules/content-engine/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/content-library/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/content-library',
                '!@/modules/content-library/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/content-performance/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/content-performance',
                '!@/modules/content-performance/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/content-publishing/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/content-publishing',
                '!@/modules/content-publishing/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/crm/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/crm',
                '!@/modules/crm/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/crm-engine/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/crm-engine',
                '!@/modules/crm-engine/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/customer-health/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/customer-health',
                '!@/modules/customer-health/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/dashboard/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/dashboard',
                '!@/modules/dashboard/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/evolution/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/evolution',
                '!@/modules/evolution/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/expansion/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/expansion',
                '!@/modules/expansion/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/experience/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/experience',
                '!@/modules/experience/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/franchise/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/franchise',
                '!@/modules/franchise/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/funnel/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/funnel',
                '!@/modules/funnel/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/growth-loop/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/growth-loop',
                '!@/modules/growth-loop/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/growth-roadmap/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/growth-roadmap',
                '!@/modules/growth-roadmap/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/i18n/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/i18n',
                '!@/modules/i18n/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/interview-authority/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/interview-authority',
                '!@/modules/interview-authority/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/journey/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/journey',
                '!@/modules/journey/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/journey-engine/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/journey-engine',
                '!@/modules/journey-engine/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/lead-engine/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/lead-engine',
                '!@/modules/lead-engine/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/lead-magnet/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/lead-magnet',
                '!@/modules/lead-magnet/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/localization/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/localization',
                '!@/modules/localization/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/member/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/member',
                '!@/modules/member/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/mission/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/mission',
                '!@/modules/mission/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/mission-engine/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/mission-engine',
                '!@/modules/mission-engine/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/mission-workspace/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/mission-workspace',
                '!@/modules/mission-workspace/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/optimization/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/optimization',
                '!@/modules/optimization/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/payments/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/payments',
                '!@/modules/payments/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/personalization/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/personalization',
                '!@/modules/personalization/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/product-experience/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/product-experience',
                '!@/modules/product-experience/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/referral/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/referral',
                '!@/modules/referral/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/retention/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/retention',
                '!@/modules/retention/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/revenue-activation/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/revenue-activation',
                '!@/modules/revenue-activation/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/revenue-drivers/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/revenue-drivers',
                '!@/modules/revenue-drivers/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/saas/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/saas',
                '!@/modules/saas/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/sales-engine/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/sales-engine',
                '!@/modules/sales-engine/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/social-setup/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/social-setup',
                '!@/modules/social-setup/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/team/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/team',
                '!@/modules/team/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/team-engine/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/team-engine',
                '!@/modules/team-engine/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/tenant/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/tenant',
                '!@/modules/tenant/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/traffic-engine/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/traffic-engine',
                '!@/modules/traffic-engine/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/user-evolution/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/user-evolution',
                '!@/modules/user-evolution/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/user-success/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/user-success',
                '!@/modules/user-success/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/value/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/value',
                '!@/modules/value/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/video/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/video',
                '!@/modules/video/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/voice/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/voice',
                '!@/modules/voice/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/webinar-center/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/webinar-center',
                '!@/modules/webinar-center/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/whatsapp-ai/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/whatsapp-ai',
                '!@/modules/whatsapp-ai/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/workspace/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: [
                '@/modules/*',
                '!@/modules/workspace',
                '!@/modules/workspace/**',
                '!@/modules/ai',
                '!@/modules/ai/**',
                '!@/modules/auth',
                '!@/modules/auth/**',
              ],
              message: 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.',
            },
          ],
        },
      ],
    },
  },
];

export default boundaryOverrides;
