allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: set this to true or false
  prisma: true
  sharp: set this to true or false
  unrs-resolver: true
