import { primitiveTokens } from "./primitive-tokens";
import { semanticTokens } from "./semantic-tokens";
import { deepFreeze } from "./token-freeze";

export const componentTokens = deepFreeze({
  button: {
    primary: {
      background: semanticTokens.color.primary,
      foreground: semanticTokens.color.primaryForeground,
      hoverBackground: primitiveTokens.color.brand["700"],
      activeBackground: primitiveTokens.color.brand["800"],
      focusRing: semanticTokens.color.focusRing,
      radius: semanticTokens.radius.md,
      paddingX: semanticTokens.spacing["4"],
      paddingY: semanticTokens.spacing["2"],
      gap: semanticTokens.spacing["2"],
    },
    secondary: {
      background: semanticTokens.color.secondary,
      foreground: semanticTokens.color.secondaryForeground,
      hoverBackground: primitiveTokens.color.neutral["200"],
      activeBackground: primitiveTokens.color.neutral["300"],
      focusRing: semanticTokens.color.focusRing,
      radius: semanticTokens.radius.md,
      paddingX: semanticTokens.spacing["4"],
      paddingY: semanticTokens.spacing["2"],
      gap: semanticTokens.spacing["2"],
    },
    danger: {
      background: semanticTokens.color.danger,
      foreground: semanticTokens.color.dangerForeground,
      hoverBackground: primitiveTokens.color.danger["700"],
      activeBackground: primitiveTokens.color.danger["900"],
      focusRing: semanticTokens.color.danger,
      radius: semanticTokens.radius.md,
      paddingX: semanticTokens.spacing["4"],
      paddingY: semanticTokens.spacing["2"],
      gap: semanticTokens.spacing["2"],
    },
  },
  input: {
    background: semanticTokens.color.background,
    foreground: semanticTokens.color.foreground,
    placeholder: semanticTokens.color.mutedForeground,
    border: semanticTokens.color.border,
    borderFocus: semanticTokens.color.focusRing,
    borderError: semanticTokens.color.danger,
    radius: semanticTokens.radius.md,
    paddingX: semanticTokens.spacing["3"],
    paddingY: semanticTokens.spacing["2"],
  },
  card: {
    background: semanticTokens.color.surface,
    foreground: semanticTokens.color.foreground,
    border: semanticTokens.color.border,
    radius: semanticTokens.radius.lg,
    shadow: semanticTokens.elevation.sm,
    padding: semanticTokens.spacing["6"],
  },
  badge: {
    default: {
      background: semanticTokens.color.muted,
      foreground: semanticTokens.color.mutedForeground,
      radius: semanticTokens.radius.full,
      paddingX: semanticTokens.spacing["2"],
      paddingY: semanticTokens.spacing["1"],
    },
    success: {
      background: primitiveTokens.color.success["50"],
      foreground: primitiveTokens.color.success["700"],
      radius: semanticTokens.radius.full,
      paddingX: semanticTokens.spacing["2"],
      paddingY: semanticTokens.spacing["1"],
    },
    warning: {
      background: primitiveTokens.color.warning["50"],
      foreground: primitiveTokens.color.warning["700"],
      radius: semanticTokens.radius.full,
      paddingX: semanticTokens.spacing["2"],
      paddingY: semanticTokens.spacing["1"],
    },
    danger: {
      background: primitiveTokens.color.danger["50"],
      foreground: primitiveTokens.color.danger["700"],
      radius: semanticTokens.radius.full,
      paddingX: semanticTokens.spacing["2"],
      paddingY: semanticTokens.spacing["1"],
    },
  },
  table: {
    headerBackground: semanticTokens.color.surfaceMuted,
    rowBackground: semanticTokens.color.background,
    rowHoverBackground: primitiveTokens.color.neutral["50"],
    border: semanticTokens.color.border,
    foreground: semanticTokens.color.foreground,
    mutedForeground: semanticTokens.color.mutedForeground,
  },
  chart: {
    categoricalPalette: primitiveTokens.chart.categorical,
    grid: primitiveTokens.chart.grid,
    axis: primitiveTokens.chart.axis,
    tooltipBackground: primitiveTokens.chart.tooltip.background,
    tooltipForeground: primitiveTokens.chart.tooltip.foreground,
  },
} as const);
