import type { AuthUser } from '@/modules/auth/services/auth-service';
import type {
  AutonomousActionType,
  AutonomousExecutionAction,
  AutonomousTriggerType,
} from '../contracts/AutonomousExecution';
import { missionAgentAssistanceService } from '@/modules/mission-workspace/services/MissionAgentAssistanceService';
import { buildExecutionProjection } from './execution-projection';
import { executionQueue } from './execution-queue';
import { shouldAutoExecute } from './execution-orchestrator';
import { evaluateGuardrail, guardrailStateFor } from './guardrail-engine';
import { assertTenantOperational } from '@/modules/tenant/services/tenant-operational-guard';

type AutonomousSchedulerAction =
  | 'AUTO_GENERATE_CONTENT_DRAFT'
  | 'AUTO_GENERATE_WEEKLY_CONTENT_DRAFTS'
  | 'AUTO_GENERATE_LEAD_MAGNET_DRAFT'
  | 'AUTO_GENERATE_FUNNEL_DRAFT'
  | 'AUTO_GENERATE_CRM_FOLLOW_UP_DRAFT'
  | 'AUTO_GENERATE_OFFER_DRAFT'
  | 'AUTO_GENERATE_INTERNAL_REPORT'
  | 'AUTO_GENERATE_SOP_DRAFT'
  | 'AUTO_GENERATE_MEETING_NOTES'
  | 'AUTO_REFRESH_ANALYTICS_SUMMARY'
  | 'AUTO_GENERATE_OPPORTUNITY_REPORT';

type AgentExecutionMap = {
  actionType: AutonomousActionType;
  title: string;
  agentId?: string;
  agentActionId?: string;
};

const ACTION_MAP: Record<AutonomousSchedulerAction, AgentExecutionMap> = {
  AUTO_GENERATE_CONTENT_DRAFT: {
    actionType: 'CONTENT_GENERATION',
    title: 'Generate Content Draft',
    agentId: 'content-agent',
    agentActionId: 'generate_content',
  },
  AUTO_GENERATE_WEEKLY_CONTENT_DRAFTS: {
    actionType: 'CONTENT_GENERATION',
    title: 'Generate Weekly Content Drafts',
    agentId: 'content-agent',
    agentActionId: 'generate_content',
  },
  AUTO_GENERATE_LEAD_MAGNET_DRAFT: {
    actionType: 'LEAD_MAGNET_GENERATION',
    title: 'Generate Lead Magnet Draft',
    agentId: 'lead-magnet-agent',
    agentActionId: 'generate_lead_magnet',
  },
  AUTO_GENERATE_FUNNEL_DRAFT: {
    actionType: 'FUNNEL_GENERATION',
    title: 'Generate Funnel Draft',
    agentId: 'funnel-agent',
    agentActionId: 'create_landing_page',
  },
  AUTO_GENERATE_CRM_FOLLOW_UP_DRAFT: {
    actionType: 'CRM_UPDATE',
    title: 'Generate CRM Follow-Up Draft',
    agentId: 'crm-agent',
    agentActionId: 'follow_up_script',
  },
  AUTO_GENERATE_OFFER_DRAFT: {
    actionType: 'TASK_CREATION',
    title: 'Generate Offer Draft',
    agentId: 'offer-agent',
    agentActionId: 'offer_review',
  },
  AUTO_GENERATE_INTERNAL_REPORT: {
    actionType: 'REPORT_GENERATION',
    title: 'Generate Internal Report',
  },
  AUTO_GENERATE_SOP_DRAFT: {
    actionType: 'TASK_CREATION',
    title: 'Generate SOP Draft',
  },
  AUTO_GENERATE_MEETING_NOTES: {
    actionType: 'REPORT_GENERATION',
    title: 'Generate Meeting Notes',
  },
  AUTO_REFRESH_ANALYTICS_SUMMARY: {
    actionType: 'REPORT_GENERATION',
    title: 'Refresh Analytics Summary',
  },
  AUTO_GENERATE_OPPORTUNITY_REPORT: {
    actionType: 'REPORT_GENERATION',
    title: 'Generate Opportunity Report',
  },
};

function actionIdFor(input: {
  userId: string;
  missionId?: string;
  action: AutonomousSchedulerAction;
  triggerType: AutonomousTriggerType;
}) {
  return `auto-${input.userId}-${input.missionId ?? 'global'}-${input.triggerType}-${input.action}`;
}

function buildAction(input: {
  user: AuthUser;
  missionId?: string;
  action: AutonomousSchedulerAction;
  triggerType: AutonomousTriggerType;
  now: Date;
}): AutonomousExecutionAction {
  const mapped = ACTION_MAP[input.action];
  const guardrail = evaluateGuardrail({
    action: input.action,
    requestedBy: input.user.id,
    affectedResources: [input.missionId ?? mapped.title],
    now: input.now,
  });
  const createdAt = input.now.toISOString();

  return {
    actionId: actionIdFor({
      userId: input.user.id,
      missionId: input.missionId,
      action: input.action,
      triggerType: input.triggerType,
    }),
    decisionId: `autonomous-${input.action}`,
    actionType: mapped.actionType,
    title: mapped.title,
    reason: 'Autonomous low-risk execution generated by scheduler.',
    route: input.missionId ? `/mission/${encodeURIComponent(input.missionId)}` : undefined,
    agentId: mapped.agentId,
    triggerType: input.triggerType,
    priority: 'medium',
    executionMode: guardrail.autonomousAllowed ? 'autonomous' : 'manual',
    requiresApproval: guardrail.approvalRequired,
    estimatedImpact: 'medium',
    estimatedEffort: 'low',
    successMetric: 'Draft asset or internal result created without external impact.',
    riskClass: guardrail.risk,
    executionLevel: guardrail.executionLevel,
    approvalStatus: guardrail.approvalStatus,
    approvalExpiresAt: guardrail.expiresAt,
    guardrail,
    state: guardrailStateFor(guardrail),
    createdAt,
    updatedAt: createdAt,
    completedAt: null,
    outcome: guardrail.allowed ? undefined : guardrail.reason,
  };
}

async function executeAgentOrInternalResult(input: {
  user: AuthUser;
  missionId?: string;
  action: AutonomousSchedulerAction;
}) {
  const mapped = ACTION_MAP[input.action];
  if (!mapped.agentId || !mapped.agentActionId || !input.missionId) {
    return {
      outcome: `${mapped.title} completed as an internal workspace result.`,
      assetIds: [] as string[],
    };
  }

  const result = await missionAgentAssistanceService.invokeAgent({
    user: input.user,
    missionId: input.missionId,
    agentId: mapped.agentId,
    actionId: mapped.agentActionId,
  });

  return {
    outcome: `${mapped.title} completed. Generated asset: ${result.generatedAsset.title}.`,
    assetIds: [result.generatedAsset.id],
  };
}

export async function runAutonomousExecution(input: {
  user: AuthUser;
  action: AutonomousSchedulerAction;
  triggerType: AutonomousTriggerType;
  missionId?: string;
  now?: Date;
}) {
  await assertTenantOperational(input.user.tenantId, 'claim');
  const action = buildAction({
    user: input.user,
    missionId: input.missionId,
    action: input.action,
    triggerType: input.triggerType,
    now: input.now ?? new Date(),
  });

  await executionQueue.enqueue({
    userId: input.user.id,
    tenantId: input.user.tenantId,
    action,
  });

  if (!shouldAutoExecute(action)) {
    return buildExecutionProjection(await executionQueue.list(input.user.id, input.user.tenantId));
  }

  await executionQueue.transition({
    userId: input.user.id,
    tenantId: input.user.tenantId,
    actionId: action.actionId,
    state: 'executing',
    outcome: 'Autonomous execution started.',
  });

  try {
    await assertTenantOperational(input.user.tenantId, 'pre_side_effect');
    const result = await executeAgentOrInternalResult({
      user: input.user,
      missionId: input.missionId,
      action: input.action,
    });
    await executionQueue.transition({
      userId: input.user.id,
      tenantId: input.user.tenantId,
      actionId: action.actionId,
      state: 'completed',
      outcome: result.outcome,
      assetIds: result.assetIds,
    });
  } catch (error) {
    await executionQueue.transition({
      userId: input.user.id,
      tenantId: input.user.tenantId,
      actionId: action.actionId,
      state: 'failed',
      outcome: error instanceof Error ? error.message : 'Autonomous execution failed.',
    });
  }

  return buildExecutionProjection(await executionQueue.list(input.user.id, input.user.tenantId));
}

export const autonomousScheduler = {
  run: runAutonomousExecution,
};
