export const CANONICAL_ROUTES = {
  dashboard: '/dashboard',
  journey: '/journey',
  brandInterview: '/brand-builder/step/interview',
  brandProfile: '/brand-builder/step/profile',
  brandBuilderProfile: '/brand-builder/profile',
  contentEngine: '/content-engine',
  leadMagnet: '/lead-magnet',
  funnel: '/funnel',
  trafficEngine: '/traffic-engine',
  leads: '/leads',
  crm: '/crm',
  sales: '/sales',
  whatsappAi: '/whatsapp-ai',
  ceoMode: '/ceo-mode',
  team: '/team',
  teamGrowth: '/team/growth',
  aiWorkforce: '/ai-workforce',
} as const;
