import type { AuthUser } from '@/modules/auth/services/auth-service';
import { getRouterForTenant } from '../router';
import { enforceQuota } from '../usage/quota';
import { logAIUsage } from '../usage/tracker';
import { composeGenerationSystemPrompt } from './context';
import {
  GENERATION_DEGRADE_LABEL,
  type GenerationOutcome,
  type RunGenerationOptions,
} from './types';

/**
 * Executes the standard AI generation pipeline once for all generation modules.
 * Failures always return a labelled fallback outcome instead of pretending that
 * template output was generated by AI.
 */
export async function runGeneration<T>(
  user: Pick<AuthUser, 'id' | 'tenantId'>,
  options: RunGenerationOptions<T>,
): Promise<GenerationOutcome<T>> {
  try {
    await enforceQuota(user.tenantId);

    const router = await getRouterForTenant(user.tenantId);
    const result = await router.generate(
      {
        systemPrompt: composeGenerationSystemPrompt(options.context),
        userMessage: options.userMessage,
        temperature: options.temperature,
        maxTokens: options.maxTokens,
      },
      options.taskCategory,
    );

    await logAIUsage({
      tenantId: user.tenantId,
      userId: user.id,
      feature: options.feature,
      result,
      routing: result.routing,
    });

    return {
      status: 'success',
      source: 'ai',
      value: options.parse ? options.parse(result.text) : result.text as T,
      text: result.text,
      result,
    };
  } catch (error) {
    return {
      status: 'degraded',
      source: 'template_fallback',
      value: options.fallback,
      userVisibleLabel: GENERATION_DEGRADE_LABEL,
      reason: error instanceof Error ? error.message : String(error),
    };
  }
}
