import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const MODULES_DIR = path.join(process.cwd(), 'src/modules');
const OUTPUT_FILE = path.join(process.cwd(), 'eslint-boundaries.config.mjs');
const CHECK = process.argv.includes('--check');
const WRITE = process.argv.includes('--write') || !CHECK;
const MESSAGE = 'Module code should avoid cross-module imports unless routed through approved shared layers such as @/lib, @/components, @/modules/ai, @/modules/auth, or its own module boundary.';

function getModules() {
  return readdirSync(MODULES_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));
}

function generateBoundaryConfig(modules: string[]) {
  const overrides = modules.map((moduleName) => {
    const group = Array.from(new Set([
      '@/modules/*',
      `!@/modules/${moduleName}`,
      `!@/modules/${moduleName}/**`,
      '!@/modules/ai',
      '!@/modules/ai/**',
      '!@/modules/auth',
      '!@/modules/auth/**',
    ]));

    return [
      '  {',
      `    files: ['src/modules/${moduleName}/**/*.{ts,tsx}'],`,
      '    rules: {',
      "      'no-restricted-imports': [",
      "        'warn',",
      '        {',
      '          patterns: [',
      '            {',
      '              group: [',
      ...group.map((pattern) => `                '${pattern}',`),
      '              ],',
      `              message: '${MESSAGE}',`,
      '            },',
      '          ],',
      '        },',
      '      ],',
      '    },',
      '  },',
    ].join('\n');
  });

  return [
    '// This file is generated by scripts/generate-eslint-boundaries.ts.',
    '// Run `pnpm lint:boundaries:check` to verify it is in sync with src/modules.',
    '',
    'const boundaryOverrides = [',
    overrides.join('\n'),
    '];',
    '',
    'export default boundaryOverrides;',
    '',
  ].join('\n');
}

const nextContent = generateBoundaryConfig(getModules());

if (CHECK) {
  const currentContent = existsSync(OUTPUT_FILE) ? readFileSync(OUTPUT_FILE, 'utf8') : '';
  if (currentContent !== nextContent) {
    console.error('eslint-boundaries.config.mjs is out of sync with src/modules.');
    console.error('Run `pnpm tsx scripts/generate-eslint-boundaries.ts --write` and commit the result.');
    process.exit(1);
  }
  console.log('eslint-boundaries.config.mjs is in sync.');
  process.exit(0);
}

if (WRITE) {
  writeFileSync(OUTPUT_FILE, nextContent);
  console.log(`Wrote ${path.relative(process.cwd(), OUTPUT_FILE)}.`);
}
